jwt:
  service_key: service_key
  api_key: |
    -----BEGIN CERTIFICATE-----
    MIIE2TCCAsGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCYxDjAMBgNVBAoTBWFk
    bWluMRQwEgYDVQQDDAtjZXJ0X3AzbWg4YTAeFw0yNTAxMTEwMzQ2NDdaFw00NTAx
    MTEwMzQ2NDdaMCYxDjAMBgNVBAoTBWFkbWluMRQwEgYDVQQDDAtjZXJ0X3AzbWg4
    YTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALbM2jkaV6PlWkIAAh5S
    eFPKhUjMaNVUgLQHdUhjx0b32JQj+NXZ5wSuxIAG/PltRd6gvNrwJQJTk3ur49yJ
    khcdFi6Y66lUwtTVndE5swDAquT+LPM7VOUGTt6pgaeN4edw5wbl6uaKXjQwmSTp
    zvSlTY0CyXZ5RsM0WuauFaST2WKHv/MrH6PhiW+RQP1G9wTK2Knqs2O7ACWxBQnQ
    ByqqSRFKeZweXqMqVm/kQTRlgY2UHXEdxU1+SseF3k7IIlTdhsKSiXiy4qKfFvdR
    tj0XaoaVo4ZzQgjVQobCsi0r251PxwRPc1tAhiKSVCvAwo0yG045lSV3zrcoBwVt
    Vrruv4R5XIEU5UOWgNnHCznOCmapeh9AiGbi/x4RjUrlOdYexia31PuE/ICPtYP2
    0ERrWbYx+axMBS8hdNvaoGpdoDxbzLOoYRL++OhubMPSE//R4vg0ttwXSey5PxoV
    DAsOEAk9E6WJoUqQHe+/RePXNncb49BG/J51JSVGe7ZrT/YsX6hXYnoOmDr4Sx2n
    1mj+Za+TRRJ6SisjI91NMUGksossZcXkyEXO33xmF6DZvG9yrTBgXcM8U04Re/QV
    4FLOlHbwYcDGcEduoJ2mJoUpOZg5nG1LcmZW0IGgC0c0unvY0dfoEq1l66nJZsbI
    tnpgsHw+CL9q+73Z73NeIzwVAgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAwDQYJKoZI
    hvcNAQELBQADggIBAFbnEIdGjm/ZMjYFf1rX1ZR35UMroeAnxntFjxMD+dgqq3z5
    rfCCYxXbKTPHtgTIJKJ3/MapOVMuzKvG7kpllytivbFA6TmonY2XDUgyc1VTNsPU
    +XQpD2YE8WTx11GPFeVPBmue1iKzAWsuG7UI3AgS3clj0V2octiWhpVD0L4RIRON
    1HkUr9YRi5cXedZwLq9Ye6wKg72njs9uG+IUKQYybwcpfQ2tNTnIYwhbZZICYT+M
    uCTg0T5FG66RD7wtrt6suQwTXjBGeFNVs/lMsUAnTxBOgkQ3/FIm24U1N2zvGwOa
    OxPzbK4S8OPeQn9iwtjI68zb461oYZs4UC1eymeTduUwzh7MbpAYbHyowgjWNa6f
    2kCIpDb51ljyLMhjqHyJCI0eKiOeCXQBZaNgFducOy8JBls4iM8E1/PaLeRjzOFU
    ka/G50ymHDt8uFAEa5jcVZ3Vq+QdzYurNh01pZffxuaEutReBgxIJwXFIAm4z6Jv
    q+SB9lGjo8Yr7L/HTd6SgPAnH1DfdcDtmHjufOC5Ccb81xIKTRCcisXni1ybKdNO
    8j3o6oz765/Obxn9rAalM3tOsei3P6MXk5cH76NBTrMxrLImVxIsO/56yNg9Stvy
    ZcUbIxAGJ1E2dpN5WBb8Ea03FmQEcYNZ96s19pqK6Gr9mT4mhU90ieco6T/2
    -----END CERTIFICATE-----
