// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BalancesBalances struct {
	Owner       string             `json:"owner"`
	Name        string             `json:"name"`
	Balance     float64            `json:"balance"`
	Currency    string             `json:"currency"`
	CreatedTime pgtype.Timestamptz `json:"created_time"`
	UpdatedTime pgtype.Timestamptz `json:"updated_time"`
}
