// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"context"
)

type Querier interface {
	//CreatBalance
	//
	//  INSERT INTO balances.balances(owner, name, balance)
	//  VALUES ($1, $2, $3)
	//  RETURNING owner, name, balance, currency, created_time, updated_time
	CreatBalance(ctx context.Context, arg CreatBalanceParams) (BalancesBalances, error)
	//DeleteBalance
	//
	//  DELETE
	//  FROM balances.balances
	//  WHERE id = $1
	//    AND owner = $2
	//    AND name = $3
	//  RETURNING owner, name, balance, currency, created_time, updated_time
	DeleteBalance(ctx context.Context, arg DeleteBalanceParams) (BalancesBalances, error)
	//GetBalance
	//
	//  SELECT owner, name, balance, currency, created_time, updated_time
	//  FROM balances.balances
	//  WHERE owner = $1
	//    AND name = $2
	GetBalance(ctx context.Context, arg GetBalanceParams) (BalancesBalances, error)
	//UpdateBalance
	//
	//  UPDATE balances.balances
	//  SET balance = coalesce($1, balance)
	//  WHERE owner = $2
	//    AND name = $3
	//  RETURNING owner, name, balance, currency, created_time, updated_time
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (BalancesBalances, error)
}

var _ Querier = (*Queries)(nil)
