services:

  users:
    image: tiktok/users:prod
    platform: linux/amd64
    ports:
      - "30001:30001"
      - "30002:30002"
    container_name: users
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/user"
      - "-conf"
      - "/bin/configs"

  carts:
    image: tiktok/carts:prod
    platform: linux/amd64
    ports:
      - "30003:30003"
      - "30004:30004"
    container_name: carts
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/user"
      - "-conf"
      - "/bin/configs"

  checkout:
    image: tiktok/checkout:prod
    platform: linux/amd64
    ports:
      - "30005:30005"
      - "30006:30006"
    container_name: checkout
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/user"
      - "-conf"
      - "/bin/configs"

  credit_cards:
    image: tiktok/credit_cards:prod
    platform: linux/amd64
    ports:
      - "30007:30007"
      - "30008:30008"
    container_name: credit_cards
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/user"
      - "-conf"
      - "/bin/configs"

  orders:
    image: tiktok/orders:prod
    platform: linux/amd64
    ports:
      - "30009:30009"
      - "30010:30010"
    container_name: orders
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/user"
      - "-conf"
      - "/bin/configs"

  payment:
    image: tiktok/payment:prod
    platform: linux/amd64
    ports:
      - "30011:30011"
      - "30012:30012"
    container_name: payment
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/user"
      - "-conf"
      - "/bin/configs"

  products:
    image: tiktok/products:prod
    platform: linux/amd64
    ports:
      - "30013:30013"
      - "30014:30014"
    container_name: products
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/user"
      - "-conf"
      - "/bin/configs"

networks:
  app-network:
    external: true
