services:

  postgres17:
    image: postgres:17-alpine3.20
    ports:
      - "5432:5432"
    container_name: postgres17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simple_bank
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "simple_bank", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - db

  redis7:
    image: redis:7.4.1-alpine
    restart: always
    container_name: redis7
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - db

networks:
  db:
    name: db-network
