services:

  api:
    image: team/backend:prod
    # platform: linux/arm64
    ports:
      - "30001:30001"
      - "30002:30002"
    container_name: api
    restart: always
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    volumes:
      - ./app.env:/bin/app.env
      #      - # 初始化数据库
      #        init_database.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    command:
      - "/bin/main"
