services:

  user:
    build:
      context: user
      dockerfile: Dockerfile
      args:
        HTTP_PORT: 30001
        GRPC_PORT: 30002
        VERSION: v1.0.0
    platform: linux/amd64
    ports:
      - "30001:30001"
      - "30002:30002"
    container_name: user
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/tiktok?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/user"
      - "-conf"
      - "/bin/configs"

  cart:
    build:
      context: cart
      dockerfile: Dockerfile
      args:
        HTTP_PORT: 30003
        GRPC_PORT: 30004
        VERSION: v1.0.0
    platform: linux/amd64
    ports:
      - "30003:30003"
      - "30004:30004"
    container_name: cart
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/tiktok?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/cart"
      - "-conf"
      - "/bin/configs"

  checkout:
    build:
      context: checkout
      dockerfile: Dockerfile
      args:
        HTTP_PORT: 30005
        GRPC_PORT: 30006
        VERSION: v1.0.0
    platform: linux/amd64
    ports:
      - "30005:30005"
      - "30006:30006"
    container_name: checkout
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/tiktok?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/checkout"
      - "-conf"
      - "/bin/configs"

  credit_cards:
    build:
      context: credit_cards
      dockerfile: Dockerfile
      args:
        HTTP_PORT: 30007
        GRPC_PORT: 30008
        VERSION: v1.0.0
    platform: linux/amd64
    ports:
      - "30007:30007"
      - "30008:30008"
    container_name: credit_cards
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/tiktok?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/credit_cards"
      - "-conf"
      - "/bin/configs"

  order:
    build:
      context: order
      dockerfile: Dockerfile
      args:
        HTTP_PORT: 30009
        GRPC_PORT: 30010
        VERSION: v1.0.0
    platform: linux/amd64
    ports:
      - "30009:30009"
      - "30010:30010"
    container_name: order
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/tiktok?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/order"
      - "-conf"
      - "/bin/configs"

  payment:
    build:
      context: payment
      dockerfile: Dockerfile
      args:
        HTTP_PORT: 30011
        GRPC_PORT: 30012
        VERSION: v1.0.0
    platform: linux/amd64
    ports:
      - "30011:30011"
      - "30012:30012"
    container_name: payment
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/tiktok?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/payment"
      - "-conf"
      - "/bin/configs"

  product:
    build:
      context: product
      dockerfile: Dockerfile
      args:
        HTTP_PORT: 30013
        GRPC_PORT: 30014
        VERSION: v1.0.0
    platform: linux/amd64
    ports:
      - "30013:30013"
      - "30014:30014"
    container_name: product
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/tiktok?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/product"
      - "-conf"
      - "/bin/configs"

  address:
    build:
      context: address
      dockerfile: Dockerfile
      args:
        HTTP_PORT: 30015
        GRPC_PORT: 30016
        VERSION: v1.0.0
    platform: linux/amd64
    ports:
      - "30015:30015"
      - "30016:30016"
    container_name: address
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/tiktok?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/address"
      - "-conf"
      - "/bin/configs"

  balance:
    build:
      context: balance
      dockerfile: Dockerfile
      args:
        HTTP_PORT: 30017
        GRPC_PORT: 30018
        VERSION: v1.0.0
    platform: linux/amd64
    ports:
      - "30017:30017"
      - "30018:30018"
    container_name: balance
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres17:5432/tiktok?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
    command:
      - "/bin/balance"
      - "-conf"
      - "/bin/configs"

networks:
  app-network:
    external: true
