# Looking for information on environment variables?
# We don't declare them here — take a look at our docs.
# https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

FROM nginx:1.27.2-alpine

ARG PORT=8080

RUN apk update && apk add --no-cache "nodejs>=18.20.1-r0 "

LABEL maintainer="mandala"

ENV API_KEY="**None**" \
    SWAGGER_JSON="" \
    PORT="8080" \
    PORT_IPV6="" \
    BASE_URL="/" \
    SWAGGER_JSON_URL="simple_bank.swagger.json" \
    CORS="true" \
    EMBEDDING="false"

COPY --chown=nginx:nginx --chmod=0666 ./manifests/swagger/default.conf.template ./manifests/swagger/cors.conf ./manifests/swagger/embedding.conf /etc/nginx/templates/

COPY --chmod=0666 ./doc/swagger/* /usr/share/nginx/html/
COPY --chmod=0555 ./manifests/swagger/docker-entrypoint.d/ /docker-entrypoint.d/
COPY --chmod=0666 ./manifests/swagger/configurator /usr/share/nginx/configurator

# Simulates running NGINX as a non root; in future we want to use nginxinc/nginx-unprivileged.
# In future we will have separate unpriviledged images tagged as v5.1.2-unprivileged.
RUN chmod 777 /usr/share/nginx/html/ /etc/nginx/conf.d/ /etc/nginx/conf.d/default.conf /var/cache/nginx/ /var/run/

EXPOSE $PORT
