// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"context"
)

type Querier interface {
	//CreateUser
	//
	//  insert into users(email, password)
	//  values ($1, $2)
	//  returning id, email, password, create_at, update_at
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
