// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"context"
)

type Querier interface {
	//CreateUser
	//
	//  INSERT INTO users(email, password)
	//  VALUES ($1, $2)
	//  RETURNING id, email, password, create_at, update_at
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	//LoginUser
	//
	//  SELECT id, email, password, create_at, update_at
	//  FROM users
	//  WHERE email = $1
	LoginUser(ctx context.Context, email string) (Users, error)
}

var _ Querier = (*Queries)(nil)
