server:
  http:
    addr: 0.0.0.0:30009
    timeout: 5s
  grpc:
    addr: 0.0.0.0:30010
    timeout: 5s

data:
  database:
    source: postgresql://postgres:postgres@localhost:5432/tiktok?sslmode=disable&search_path=products
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 4.2s
    write_timeout: 4.2s
    dial_timeout: 4s
