// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

type Products struct {
	ID          int32    `json:"ID"`
	Name        string   `json:"Name"`
	Description string   `json:"Description"`
	Picture     string   `json:"Picture"`
	Price       float32  `json:"Price"`
	Categories  []string `json:"Categories"`
}
