// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: product.sql

package data

import (
	"context"
)

const CreateProduct = `-- name: CreateProduct :one
INSERT INTO products(name,description,picture,price,categories)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, picture, price, categories
`

type CreateProductParams struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Picture     string   `json:"picture"`
	Price       float32  `json:"price"`
	Categories  []string `json:"categories"`
}

// CreateProduct
//
//	INSERT INTO products(name,description,picture,price,categories)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, name, description, picture, price, categories
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Products, error) {
	row := q.db.QueryRow(ctx, CreateProduct,
		arg.Name,
		arg.Description,
		arg.Picture,
		arg.Price,
		arg.Categories,
	)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Picture,
		&i.Price,
		&i.Categories,
	)
	return i, err
}
