// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"context"
)

type Querier interface {
	//CreateProduct
	//
	//  INSERT INTO products(name, description, picture, price, categories)
	//  VALUES ($1, $2, $3, $4, $5)
	//  RETURNING id, name, description, picture, price, categories
	CreateProduct(ctx context.Context, arg CreateProductParams) (Products, error)
	//ListProducts
	//
	//  SELECT id,
	//         name,
	//         description,
	//         picture,
	//         price,
	//         categories
	//  FROM products
	//  WHERE $1 = ANY (categories)
	//  ORDER BY id
	//  OFFSET $2 LIMIT $3
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Products, error)
}

var _ Querier = (*Queries)(nil)
