// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"credit_cards/internal/biz"
	"credit_cards/internal/conf"
	"credit_cards/internal/data"
	"credit_cards/internal/server"
	"credit_cards/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	pool := data.NewDB(confData)
	client := data.NewCache(confData)
	dataData, cleanup, err := data.NewData(logger, pool, client)
	if err != nil {
		return nil, nil, err
	}
	creditCardsRepo := data.NewCreditCardsRepo(dataData, logger)
	creditCardsUsecase := biz.NewCreditCardsUsecase(creditCardsRepo, logger)
	creditCardsServiceService := service.NewCreditCardsServiceService(creditCardsUsecase)
	grpcServer := server.NewGRPCServer(confServer, creditCardsServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, creditCardsServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
