server:
  http:
    addr: 0.0.0.0:30005
    timeout: 1s
  grpc:
    addr: 0.0.0.0:30006
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgresql://postgres:msdnmm@node1.apikv.com:5432/tiktok?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    username: default
    password: msdnmm
    read_timeout: 5.2s
    write_timeout: 5.2s
    dial_timeout: 5s
