# 可观测性
jaeger:
  service_name: tiktok_e-commence_credit_cards
  grpc:
    # endpoint: localhost:4317
    endpoint: node10.apikv.com:32163
  http:
    # endpoint: localhost:4318
    endpoint: node10.apikv.com:32163
