# 可观测性
jaeger:
  service_name: tiktok_e-commence_checkout
  grpc:
    # endpoint: localhost:4317
    endpoint: node7.apikv.com:30163
  http:
    # endpoint: localhost:4318
    endpoint: node7.apikv.com:30410
