apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  # - ingress-http.yaml
  # - ingress-grpc.yaml

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
