apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 引用的资源清单
resources:
- ../../user
# - ../../product

# 文件前缀
# namePrefix: prod-

# 文件后缀
#nameSuffix: "-001"

components:
  # - ../../components/replicas
  - ../../components/env-vars
  - ../../components/limits

# 修改或添加的配置
patches:
- path: add-env.yaml
- path: replica_count.yaml
- path: limits.yaml
