server:
  http:
    addr: 0.0.0.0:30009
    timeout: 1s
  grpc:
    addr: 0.0.0.0:30010
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgresql://postgres:msdnmm@node1.apikv.com:5432/tiktok?sslmode=disable&timezone=Asia/Shanghai
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 5.2s
    write_timeout: 5.2s
    dial_timeout: 5s
