apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commence-user-swagger
  labels:
    app: e-commence-user-swagger
spec:
  template:
    spec:
      containers:
        - name: e-commence-user-swagger
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"

