// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"user/internal/biz"
	"user/internal/conf"
	"user/internal/data"
	"user/internal/server"
	"user/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, casdoor *conf.Casdoor, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewCache(confData)
	casdoorsdkClient := data.NewCasdoor(casdoor)
	dataData, cleanup, err := data.NewData(logger, client, casdoorsdkClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userServiceService := service.NewUserServiceService(userUsecase)
	grpcServer := server.NewGRPCServer(confServer, userServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, userServiceService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
