apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commence-user-swagger
  labels:
    app: e-commence-user-swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commence-user-swagger
  template:
    metadata:
      name: e-commence-user-swagger
      labels:
        app: e-commence-user-swagger
    spec:
      containers:
        - name: e-commence-user-swagger
          image: example
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      restartPolicy: Always
