apiVersion: v1
kind: Service
metadata:
  name: swagger-e-commence-user-service
spec:
  selector:
    app: e-commence-user-swagger
  ports:
    - name: http
      port: 8080
      nodePort: 30006
      protocol: TCP
      targetPort: 8080
  type: NodePort

