apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  # - issuer.yaml
  - ingress-http.yaml
  - ingress-grpc.yaml

# 命名空间
namespace: bank

# 标签
#commonLabels:
#  app: bingo
#commonAnnotations:
#  oncallPager: 800-555-1212
