apiVersion: v1
kind: Service
metadata:
  name: e-commence-product-service
spec:
  selector:
    app: e-commence-product
  ports:
    - name: http
      port: 30013
      protocol: TCP
      targetPort: 30013
      nodePort: 30013
    - name: grpc
      port: 30014
      protocol: TCP
      targetPort: 30014
      nodePort: 30014
  type: NodePort

