// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.2
// - protoc             v5.28.3
// source: checkout/v1/checkout.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCheckoutServiceCheckout = "/api.checkout.v1.CheckoutService/Checkout"

type CheckoutServiceHTTPServer interface {
	Checkout(context.Context, *CheckoutReq) (*CheckoutResp, error)
}

func RegisterCheckoutServiceHTTPServer(s *http.Server, srv CheckoutServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/checkout", _CheckoutService_Checkout0_HTTP_Handler(srv))
}

func _CheckoutService_Checkout0_HTTP_Handler(srv CheckoutServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckoutReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCheckoutServiceCheckout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Checkout(ctx, req.(*CheckoutReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckoutResp)
		return ctx.Result(200, reply)
	}
}

type CheckoutServiceHTTPClient interface {
	Checkout(ctx context.Context, req *CheckoutReq, opts ...http.CallOption) (rsp *CheckoutResp, err error)
}

type CheckoutServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCheckoutServiceHTTPClient(client *http.Client) CheckoutServiceHTTPClient {
	return &CheckoutServiceHTTPClientImpl{client}
}

func (c *CheckoutServiceHTTPClientImpl) Checkout(ctx context.Context, in *CheckoutReq, opts ...http.CallOption) (*CheckoutResp, error) {
	var out CheckoutResp
	pattern := "/v1/checkout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCheckoutServiceCheckout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
