server:
  http:
    addr: 0.0.0.0:30013
    timeout: 5s
  grpc:
    addr: 0.0.0.0:30014
    timeout: 5s

data:
  database:
    source: postgresql://postgres:msdnmm@node1.apikv.com:5432/tiktok?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 4.2s
    write_timeout: 4.2s
    dial_timeout: 4s
