// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

type CreditCardsCreditCards struct {
	ID              int32  `json:"id"`
	Owner           string `json:"owner"`
	Name            string `json:"name"`
	Number          string `json:"number"`
	Cvv             string `json:"cvv"`
	ExpirationYear  string `json:"expiration_year"`
	ExpirationMonth string `json:"expiration_month"`
}
