server:
  http:
    addr: 0.0.0.0:30001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:30002
    timeout: 1s
data:
  redis:
    addr: localhost:6379
    username: default
    password: msdnmm
    read_timeout: 4.2s
    write_timeout: 4.2s
    dial_timeout: 4s

casdoor:
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIE2TCCAsGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCYxDjAMBgNVBAoTBWFk
    bWluMRQwEgYDVQQDDAtjZXJ0X3ZpaXBvYTAeFw0yNDEyMDIwNDIyMjNaFw00NDEy
    MDIwNDIyMjNaMCYxDjAMBgNVBAoTBWFkbWluMRQwEgYDVQQDDAtjZXJ0X3ZpaXBv
    YTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMO/H9wQm8uTkAJGd19C
    r96Y5lzKrjwcbfgDUQc5m4naZXg+ufIrMt0DaNwsAyPoUdNGrA98shArPVYC0XMT
    6pW+Bmiv17kpdlYtAJx0m98CrMZgC1ie0d0XBu1Cg13cVUzm8a8y66y9HyuoBOTx
    4+2+aY73G/D2samM8x5HsP7KiDHK/qfFg+P/u704PyI3fENzzQTA+T93O1H7sCoy
    iDPsSkkAoEWu6jQ7Mc1zYsU9UTLUni1LaxaRXYrvJcuG+6269EtXmG2NmfQXuAeE
    Q/xocHZqGjd8UpNBNqzUIaKr4rDekf+yqBR3i04VKHmFaCTLK+D13JzZH0B/BiXc
    UdV1nDOj4HBCliUOPZWcrek3tOGkip0cSodlwBu1p5ODFx+RLFgxJMJFKxOrbIaL
    hJ6X5BxfF1iIfIWEsUaHdIt9Osi9uUp4oHo54elhraaTEITOuWggKWeyaYEd1xvB
    vMpdtQazhTPTeEc/PdpXBF4aM7y1Zy6h/L3D5LDUEuERsVHvi7YWxrC07kEIYIis
    3VUCOUgk963g1RU1OE9fevKnb+NkBwO6jP8YdpL1laOwsIl6Br24BG7PDF5ZEZHM
    lGWykHl4KC4sCkYXrtCGG4Qjqk+wxp7Bk8RmdpXz0XaKtGIat00Vy4XnoAATTLwM
    xiEXcsJ6tc+eunzMobbuz2jhAgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAwDQYJKoZI
    hvcNAQELBQADggIBAEVhcFl55xOs7zhrOQoyl23S3DXXOjezBadeQOm/tGYGbM/g
    lvbPRNYmrotcprYZu7HuLpyVyjvEKVS1RWSHyRAGFDyCuTAL2afjxhTx7lu4f7dM
    +EqoDKcnb62Ekf4C4kY+KeyCamAc6svKHjBe415jQwhbJxrp7Wduae//wUKM5vA9
    X/CoY1grtQY+kG0qE6fBPoRD5tV242CyH0es7aVm2n8HIDR0TdWhWWczYiPT4H/k
    hA62x26wUTkFi+Dzan4y4zCIjzqVfPsepuUGW0sSlUKVgX9GbMgmES/F6apu3Xun
    7+Vq+mXXcQM2vIBgXlZlrNMGDC3hRdqPVCrLhRLmf0Wicr6cXqe1jjTAfcLL5dcm
    J8G+a/LrrPQqQ3csCvsfEGb+Nl22nzd1kKi/URBcnB0Oc6xCtS/gtOxdLsCaAsdP
    XqYj43rUKDG4qOpfFWum7Het32xqQTd7DbZaaZWX1bgtDFUP+jlIWjNdecoJRYuQ
    olOKaz3+vsEWnUZvIWw66xW+r0EBSnn8xbfw3+pHmJONwvgcCw9eSsRVNBdSEDui
    ImY6Yvq+tKz/ieIbNNjhjcAmzU48OstD/5b68lSAjMloC71ulukc7zdvyvalaI5J
    DbhfNYoQdufXTD3+Daj+RsfedJt8LQwbUmrPsZYXnPyIZR8ku+VKfJ5o1nsd
    -----END CERTIFICATE-----
  server:
    # casdoor url
    # endpoint: "http://localhost:8000"
    endpoint: "http://node9.apikv.com:30251"
    client_id: "58ae47eed5903ca1c3ce"
    client_secret: "d092bd2b51a075fe7a790e01e8a2b1a8176a2d40"
    organization: "tiktok"
    application: "e-commence"
