consul:
  # address: node8.apikv.com:32080 # NodePort 外网可访问的Consul HTTP API地址
  # address: http://node15.apikv.com:8500 # NodePort 外网可访问的Consul HTTP API地址
  # address: http://192.168.3.12:32080 # NodePort 外网可访问的Consul HTTP API地址
  address: node1.apikv.com:8500 # NodePort 外网可访问的Consul HTTP API地址
  scheme: http
  healthCheck: false
