// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package modules

import (
	"time"
)

type CartsCartItems struct {
	ID        int32     `json:"ID"`
	UserID    string    `json:"UserID"`
	CartID    int32     `json:"CartID"`
	ProductID int32     `json:"ProductID"`
	Quantity  int32     `json:"Quantity"`
	CreatedAt time.Time `json:"CreatedAt"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}

type CartsCarts struct {
	ID        int32     `json:"ID"`
	UserID    string    `json:"UserID"`
	CreatedAt time.Time `json:"CreatedAt"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
