// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package modules

type CheckoutCheckout struct {
	ID           int32  `json:"id"`
	UserID       string `json:"userID"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	Email        string `json:"email"`
	AddressID    int32  `json:"addressID"`
	CreditCardID int32  `json:"creditCardID"`
}
