// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package modules

import (
	"context"
)

type Querier interface {
	//CreateCheckout
	//
	//  INSERT INTO checkout.checkout(user_id, firstname, lastname, email, address_id, credit_card_id)
	//  VALUES ($1, $2, $3, $4, $5, $6)
	//  RETURNING id, user_id, firstname, lastname, email, address_id, credit_card_id
	CreateCheckout(ctx context.Context, arg CreateCheckoutParams) (CheckoutCheckout, error)
}

var _ Querier = (*Queries)(nil)
