// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"time"
)

type PaymentPayments struct {
	ID                        int32     `json:"id"`
	SnowflakeID               int64     `json:"snowflakeID"`
	Owner                     string    `json:"owner"`
	Name                      string    `json:"name"`
	Amount                    float64   `json:"amount"`
	OrderID                   int32     `json:"orderID"`
	CreditCardNumber          string    `json:"creditCardNumber"`
	CreditCardCvv             string    `json:"creditCardCvv"`
	CreditCardExpirationYear  string    `json:"creditCardExpirationYear"`
	CreditCardExpirationMonth string    `json:"creditCardExpirationMonth"`
	Status                    string    `json:"status"`
	CreatedAt                 time.Time `json:"createdAt"`
}
