// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentPayments struct {
	ID                   int32          `json:"id"`
	SnowflakeID          int64          `json:"snowflakeID"`
	Owner                string         `json:"owner"`
	Name                 string         `json:"name"`
	Amount               pgtype.Numeric `json:"amount"`
	OrderID              int32          `json:"orderID"`
	CreditCardNumber     string         `json:"creditCardNumber"`
	CreditCardExpiration pgtype.Date    `json:"creditCardExpiration"`
	Status               string         `json:"status"`
	CreatedAt            time.Time      `json:"createdAt"`
}
