// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"time"
)

type OrdersOrderItems struct {
	ID        int32 `json:"id"`
	OrderID   int32 `json:"order_id"`
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
	Cost      int32 `json:"cost"`
}

type OrdersOrders struct {
	ID        int32     `json:"id"`
	Owner     string    `json:"owner"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	AddressID int32     `json:"address_id"`
	Currency  string    `json:"currency"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
