// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"context"
)

type Querier interface {
	//CreateOrder
	//
	//  INSERT INTO orders.orders (owner, name, email, address_id, currency, created_at)
	//  VALUES ($1, $2, $3, $4, $5, now())
	//  RETURNING id
	CreateOrder(ctx context.Context, arg CreateOrderParams) (int32, error)
	//CreateOrderItems
	//
	//  INSERT INTO orders.order_items(order_id, product_id, quantity, cost)
	//  VALUES ($1, $2, $3, $4)
	//  RETURNING id, order_id, product_id, quantity, cost
	CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) (OrdersOrderItems, error)
	//ListOrderItems
	//
	//  SELECT id, order_id, product_id, quantity, cost
	//  FROM orders.order_items
	//  WHERE order_id = $1
	ListOrderItems(ctx context.Context, orderID int32) ([]OrdersOrderItems, error)
	//ListOrders
	//
	//  SELECT id, owner, name, email, address_id, currency, status, created_at, updated_at
	//  FROM orders.orders
	//  WHERE owner = $1
	//    AND name = $2
	//  ORDER BY updated_at
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]OrdersOrders, error)
	//MarkOrderPaid
	//
	//  UPDATE orders.orders
	//  SET status     = 'paid',
	//      updated_at = now()
	//  WHERE id = $1
	//    AND owner = $2
	//    AND name = $3
	//  RETURNING id, owner, name, email, address_id, currency, status, created_at, updated_at
	MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (OrdersOrders, error)
}

var _ Querier = (*Queries)(nil)
