// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package modules

import (
	"time"
)

type CartsCartItems struct {
	ID        int32     `json:"ID"`
	Owner     string    `json:"Owner"`
	Name      string    `json:"Name"`
	ProductID int32     `json:"ProductID"`
	Quantity  int32     `json:"Quantity"`
	CreatedAt time.Time `json:"CreatedAt"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
