// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package modules

import (
	"time"
)

type AddressesAddresses struct {
	ID            int32  `json:"ID"`
	UserID        string `json:"UserID"`
	StreetAddress string `json:"StreetAddress"`
	City          string `json:"City"`
	State         string `json:"State"`
	Country       string `json:"Country"`
	ZipCode       int32  `json:"ZipCode"`
}

type OrdersOrders struct {
	ID           int32     `json:"ID"`
	Email        string    `json:"Email"`
	UserID       string    `json:"UserID"`
	UserCurrency string    `json:"UserCurrency"`
	CreatedAt    time.Time `json:"CreatedAt"`
	UpdatedAt    time.Time `json:"UpdatedAt"`
}
