// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package modules

import (
	"context"
)

const CreateOrder = `-- name: CreateOrder :one
INSERT INTO orders.orders (email, user_id, address_id, user_currency)
VALUES ($1, $2, $3, $4)
RETURNING id, email, user_id, user_currency, created_at, updated_at
`

type CreateOrderParams struct {
	Email        *string `json:"Email"`
	UserID       *string `json:"UserID"`
	AddressID    *int32  `json:"AddressID"`
	UserCurrency *string `json:"UserCurrency"`
}

// CreateOrder
//
//	INSERT INTO orders.orders (email, user_id, address_id, user_currency)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, email, user_id, user_currency, created_at, updated_at
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (OrdersOrders, error) {
	row := q.db.QueryRow(ctx, CreateOrder,
		arg.Email,
		arg.UserID,
		arg.AddressID,
		arg.UserCurrency,
	)
	var i OrdersOrders
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.UserCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
