casdoor:
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk
    bWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTI0MTExNTAwMzMxMloXDTQ0
    MTExNTAwMzMxMlowKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp
    bHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDIwYENThj9JGWl
    1f8o5Uh84ld/J5Ve33nl/xuXASttRPDvQpmoLfj6RU0TXEOO7IkePQemEzSc9cay
    WX/CmhtCj/19FMviaoItMlRrSOIzARKo8XXnkfCZZpjkjGbMNtz/LrHCx8tz8rkp
    WlVyBlykgXp4IJbK9a0ALHHZR6wRWVmH/Loz4DxQpomA9HEikxKzOu9bmBVxsEUK
    DSEbi1ZXpxwmANOZGq4AlQLTqZAIjnVO7vya7Gu/kU8MjgeViJ61Ri3v/MdftBGh
    KudYCWXRbJW58hepuI1MS4d6ByXMlHOPl8cqPBGL1IJTQyZTDL+YDzFiRSTP10Ic
    BirfaQwJR16ji7r//WMn4AlhAftUU8LZk1FBfP0UZoYympRHOUP7xQx0fZbeLNIl
    q9iCh0yU9vctXf4ErhY5NalxEoMzzKSsu6aSyV4q72WyaI4xIwADjS/bbtYDCw6C
    9ztruRJ5aIWA5rNGtZjE81Z15vaeO3gELb344dJMq83c4Vk4wjCKvm7M3spmLBTc
    8kHKs1wLOcQA/r2gQHYmDYf+nfXIowvaXdGZaFPFR1Krdpx1PzaubaeG7dnPMPzl
    6AhUTDDQoEI0/MFNTfsLAqd+zQ6o4jN8EyoiA8ncTQ9Ze94wE1TNoGWnLuaiPQFF
    THj/uQN4ObQwhEKWyeMTReXiScZoWwIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G
    CSqGSIb3DQEBCwUAA4ICAQB6JnPihiM2n5SDY3GraTM/rhOqwQQm048lPPR32Clp
    xfM2LAe3tzWnoL5S2+UoJRHbhfkWHMh07033Wu0aW/Nn2ZO0NH530KpID4l8Y48Q
    UtjyPTDWn0ncqoTjcGSWJhHcPQ5etKuTTn3uc3/UBmRcQXGxxeJMkR+r1ATJPVF3
    jHxBlnlHvbaw5XOeuOuHpDoy8043EiTBze019NGXdrQo+CmdM87ItfYvFW3zImdL
    U/w+SjwXQh31364CiIUVmZDAICtnPi66zQesAij9tBl0hy3z/i2p78lkQAwn0ItI
    5z6WbGfUQnm8fVhJLCJoNSfWpr0NmEeim9ZAZDEly5hesTiJ5Xyhn/Pb2P/lAoKf
    rsIXGkUwOIw5DI6vkseO64whhZQmFX2gXraT8kC5kTaBCiSk7qECvcJS24bhcoeZ
    +cDH9Tr1s0CUsz0NaK0J8uARXiPzq1C0JRQFLGSfI4kH0Iql8CA2/jtBWz+dcvnE
    SLShmrEN0eA4MDwgCd0pfYCzG9xvthIuSfcx7u0sppzI41PFCYcKkteu9Y2KMFGS
    Sm9YNcPWoDZ3wIRMRfL3xkN8pseSMxrDiell81MzhnGBjmsq8q4h7MKRiNLfRJdQ
    jLHHSBxpUjfEWGgTtOKKt6ORSAK4oP7evo3GvXgVioPfidDI/Evz7sd5/ngcuB3l
    uA==
    -----END CERTIFICATE-----
  server:
    endpoint: "http://localhost:8000"
    client_id: "19c863e54bafc62a9ae1"
    client_secret: "829adc436f031bfe8b70419dcb65fda7d40b378a"
    organization: "tiktok"
    application: "e-commence"
    frontend_url: "http://localhost:3000"
