casdoor:
  certificate: |
   -----BEGIN CERTIFICATE-----
   MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk
   bWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTI0MTExNTIwMjU0OFoXDTQ0
   MTExNTIwMjU0OFowKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp
   bHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDvj3/5oD+QGDV4
   xw8cJQTg/rBOp0C/DbCAFGrIp8d4zfSCL3/tLT7341PgPBGs0dhi7TmNxjf/1Nox
   5daR/A7HJUTRsZtmUYvmeUFi7NaR0mmv227rQYyCcl6IPK29TV2014evCWvt2ayW
   vKy4aZOVz3SoO1NcscOExWgHEbSAC8bV5RvwW75/yq405h1IjYdMH1PtHTYlqGYu
   xOa2vwsskHaBHBI9z0IpEJ79EuPOmUTB/Ps3EmRWN4drGiwxhVAbveJAG9YC1tSM
   UGXRoBdxL/13+IZmPNOTuCakVWGxLxu6ddbIitUuNsm0NgI/R9KEm1YW4VVSrczM
   YPFL0SVS52puncvnO1fOV65rgEfrWFEoWm7y/fZjNT216Up0aglta/YC+x+SNoNF
   jks3t8WCvjQ/ADqtclTMtz1TSPA1TJIIj0Q2t8IopNx/CG+y9tePqJ+Q82i0D3MO
   bcQuVW4UUo9dSGbiqPCuyS1hl5j8wR+fOjkcwau1TkNZc+Zg6+cX4vAsyXFxGc5u
   2RjzRlPX0xooSUjXjudgGU9STT4AGqikN+zu6WWmdWGYc9050yJGLgdgweua6dTM
   dDXpU+Y5ImsO/dgGQDvjKB65VLU6abkM84QyBSl5OPNkf7/bzL+sB08aHO2Yaxdq
   EEItIX+2UX+JPx4pzPlU9mTA/l5PmQIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G
   CSqGSIb3DQEBCwUAA4ICAQC0UMcM9bZKKC2DAKNXxkbazmvaCwYUDCK1ou+Gyw89
   9Lf3t5cTK3z1CKpMpqAxbFvQ/zyL85DzGCKG5i6rYLoZ4ptroBNlORiz/zdpaQXB
   0nS/EycBsJZjKdYjKBM+vL8Hjxe3pvmB7cJ/f3i2d+OToe+Q8FzcUuo+gcNp2yNb
   VAyvs49VLzfEArc4Cwuesk8wp/Sp+DimpEczl03ew81qWbQywqAdsAki4HknHNr0
   DpII/1n5MLA4DZbknvQ6Ds8PzBp5F+unlZT/z2JkwcJWtOkRsG2hDO2thOrzKjV/
   T5N6EWGqIpO1tc04UN1uRjbBJ9DdMQj+pdKY68wvA7fCdRpfxcU7QHEPY9nWMVb7
   Am8qksQG/1PEoDca9JeT12hkjAm3ULDM0GW7IOz3S9Pyt+fj7AHNerrvgAGoUrSu
   peuyjWsRb2Ov6c85hyXusNxDyeHkglz9rVT6f/JD4aGRL1tNswvsAJBG77sttQ6U
   hMOkHin3EXwNG+aoaGnsclRfY1njBvWcP3SQBexxCKouxxIE8uqF98A1+1nDjCmJ
   LHknh1h6VAsqqteIayh927ncFuqXbUSPVtbS3vRALrbLSJrUVCrV/ueLL02DLVtG
   MrP92A4jhZ/XtyRiKkc91e796V1ZzDMF/FPYZyyvjWejQQYz8qgaU48+Q7LMdgAb
   d=
   -----END CERTIFICATE-----
server:
    endpoint: "http://localhost:8000"
    client_id: "784b2128ff0e667a88f9"
    client_secret: "774de592e3879c66f07c638a411b429a7e34a676"
    organization: "tiktok"
    application: "e-commence"
    frontend_url: "http://localhost:3000"
