server:
  http:
    addr: 0.0.0.0:30001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:30002
    timeout: 1s
data:
  database:
    source: postgresql://postgres:postgres@localhost:5432/tiktok?sslmode=disable&search_path=users
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 4.2s
    write_timeout: 4.2s
    dial_timeout: 4s

casdoor:
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIE2TCCAsGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCYxDjAMBgNVBAoTBWFk
    bWluMRQwEgYDVQQDDAtjZXJ0XzZnNWdoZzAeFw0yNDExMTYwNDM4MTJaFw00NDEx
    MTYwNDM4MTJaMCYxDjAMBgNVBAoTBWFkbWluMRQwEgYDVQQDDAtjZXJ0XzZnNWdo
    ZzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK/NDvwsr7WOnLvyVkph
    Cg21dPoj0Mj0N24zmyZMEH5T8Lkg8Fuq5YxDuTpIjoDEboWWrpJd/+zUfBwIju5+
    pIWitx106LY8S3gJdN+pDpGLYeJOHC5KEs5+fJj1GD+SRaeeZ8/kF2SSpNMq0yrQ
    lUQtFFO+c0CkB0TW3jpa1ZXxzjWEMhUBUJ7WozmIVRgZ1ruwa8GECzo8dPWKxAjM
    ikCae/BmDqmxBQ/DbNBZ7wE1J/Lr2XLnDg3zgkGYPya0Ys1Zv0YeQxDpHg82uLGl
    iCpaWCB+42Bd/sSyaL3vOLVYWrhuVPmZrq6DRzbh4Pd49BxY59CxqpLHjSrUaGw9
    p6UHrfonHt2D/hjhhzomtpRnjj/QgJgJwduYQTGlq64Pj7ICWfFexv73rNxX/gao
    VbH0MrJXLuacVu9+PQDoMYrDZthx5taTAhyokfRYIkC8hm0/o+UNReNiFX+ti4Jd
    UadjeyNHjmWej3snZBuph1/mbVRa33EQxwlJq7oMKcsb4nV13ifvJ7GgoreZCcIP
    6coAukM+Dsgb5zbMrrqG2xhLhWSggsEC2AdRo+tDZ0pZ/AdzyYxuuBmlzAO751Mk
    jC1+3kMk0panf1ddFc0Y22dIBZx6q9/qfu0woJUqVKB9umvRBe7aDHuFDdENlqb8
    JZtFlHLVOwxsJ6hvjIXNDiAvAgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAwDQYJKoZI
    hvcNAQELBQADggIBACFJ6UmMNqCrju3c9najnTjOiDzPmVYCi7usPI+lVgJMuEur
    Tq1k+ZBMsoj48dhfwJf0LMhTxdAtzER+bP+IbiCeMDjQc1AY5z/VAhdn9gdDMDzr
    taoeI2kmTDxPW+3NatqspKxRMuitAsDh+AXvAFZv9/b5ygkP3tIT+o1Brytrsbrc
    iqw33cDI2+WoHOziFu7XC8/bq1vwig5yquXrWjfeIslxJpzwxo5m/cOrm7GjMRxh
    vMlcJg5IYxKVtnwXL5QL9kSqL/GOI0t893O6ukp+7a3VRjEuqxNf2s5dRgbvIOUP
    7vzujfESOhhakCfJ6RCTf27ViEqT4U2LN+ot7l/k7eLnOST6lo0cQ1JIm2vQ6sv0
    IE6r4E1LYJjNC4if3NHCGlbvK1XXGtK9kgdldo1jArZntbuSdYE7Qoce5VFaVVQ9
    VQU9SIfKjBBFN3VrGNkLHKzlFmLqfFN9VWQqN/pSXEL+NTZAWGO18pWyCaEEPa1s
    w2roP0c07J1IafrvIssOeHNqVQ7d5KgP4s/irIR2JEwoGcPbDnFdAvxK0yJfh+zJ
    7R3w6RJcWyW5DfNmjbmNfT9cYP39OHcnZbkySd3GOqh9sKoXu7vvub3nQDakxfcN
    q9xS1nKULMWS4pOc6mA0znJadTspcyRBJjO/ca7opRRfN//EhEQE6g7D0CPZ
    -----END CERTIFICATE-----
  server:
    # casdoor url
    endpoint: "http://localhost:8000"
    client_id: "58ae47eed5903ca1c3ce"
    client_secret: "d092bd2b51a075fe7a790e01e8a2b1a8176a2d40"
    organization: "tiktok"
    application: "e-commence"
    frontend_url: "http://localhost:3000"
