server:
  http:
    addr: 0.0.0.0:30004
    timeout: 15s
  grpc:
    addr: 0.0.0.0:3006
    timeout: 15s

data:
  database:
    source: postgresql://postgres:postgres@localhost:5432/tiktok?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 4.2s
    write_timeout: 4.2s
    dial_timeout: 4s
