server:
  http:
    addr: 0.0.0.0:30001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:30002
    timeout: 1s
data:
  database:
    source: postgresql://postgres:postgres@localhost:5432/tiktok?sslmode=disable&search_path=users
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 4.2s
    write_timeout: 4.2s
    dial_timeout: 4s

casdoor:
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIE2TCCAsGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCYxDjAMBgNVBAoTBWFk
    bWluMRQwEgYDVQQDDAtjZXJ0X281MDQ0bzAeFw0yNDExMjAxNTE5MjBaFw00NDEx
    MjAxNTE5MjBaMCYxDjAMBgNVBAoTBWFkbWluMRQwEgYDVQQDDAtjZXJ0X281MDQ0
    bzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANRCkXo51UrU3yN/edz1
    +QrCKwFc+hMTxxvq3iVjbOTbRtVBXt4zM/M+oOiE7re9o6zKBtzHlmY8HyFl6ia7
    Wo4tKdEdcqphQAHUIJN5db84SaVf7KryHfzvgxbx5uHfq3jzZBmk1vy5CZVZhYra
    GGTIUzUeTQMNap/HcIPACgeI5Xe77Ec4UrVRR3t9j7EIEN4TzUXLFY+cdxmOJrvP
    zpnzNlSQrLBvlIKk+SGmp7QNUxrGxgALCdKrILK0AsAZyFnIso6TJuplxgP+6lSm
    dNxKCK6wt0wGX2dmow+LtttlK8q/QyuN2L00EXsgZHMAJui3AI8cUX/MvkSmoJ6h
    HZO4VPSSY392jUP8qadxqTLAgLQJCzCAwS1EsILqXXksm6GO7fIwsB11eIH/fHLC
    c9I3QTd7neM2SgPFHGVXnXaEVIxhqnNilzo+WbOSsK76qJuPXexRMTDJph9tZ2mE
    PmCCqTJHhPtbiVV3UoekMk3DVGizRY84prRd4lSSxvARda/TO/Lz4QPtXpDKaEYT
    Oe0ZzJflO+lwcv4eehirWUpJ1X3l/z/odn6aVNtApaeAfaBwdD/WqLld9KrbmsY3
    S98W7THwh4Gy23/5mDRTTUaLgJ/X5hJjp+wZOWIgWNqevmYrW5RF0U5GtrJ3r40p
    LtCq3ldLAoVyM/OECwmIlyuTAgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAwDQYJKoZI
    hvcNAQELBQADggIBAIPsJk0Ji6esSv/Q+bCMJCw5wj5YZSk8FoLmaS4kfrBoLn7O
    duPTHDbJKgwha1vYPayWyuL3QUO4Q92NeVNCRTxSe5dDpNyRl61OY1BvolBh/bde
    tbX8d4Lrlf5IuJ4DSeerG/tjAMMdV78sslO//RaT96d8UFZ4TBXPHGLM6n/uwA9Y
    Lt3XFqomaIcRXFgy1gkGj0rq6d8ZEIMiH0qNKeJx0K+zQ5uKfcWIUH7zHgrwfUFp
    SsliqXQYHyN3YTWqW7NJCfGllalcX76rXABlgsM8qTtJSPlMyiB5GXrWZr0Hyp+f
    S6LErBNkbUSu6/x1a0URI87qj3Hgr4qxtCmZexAb+Vhll4SebyT/eLx+nssVn3I7
    QR78dlz+erBiFbTCTeq4RB7Tq72kCKzrar1w1hiE/6Po2jxi4NuCEIoveGG3d7NR
    j3zzjil1LAU3Pf3JIQh2E0PA5qeUTeCEqBwxnwphqp+YCHld8r0RsQ7z7vxBjmqY
    K4ov780Rl4gfJ2I5KbQUUPe/uC/psqkx8DiW/EjZbXoJMyf7kGKLmWPwg8haj6nO
    JpltUodVSKkLwY3qsDHfwbWgIJSk/pVVjAlMRvPFknbcZcpv/K0pPoAPht9FStI4
    fZ6Xw2je/RreC9JClZqUPfQrd2BSyYffsI8xh5deM0txjnuqFCfDlpEE+qdT
    -----END CERTIFICATE-----
  server:
    # casdoor url
    endpoint: "http://localhost:8000"
    client_id: "58ae47eed5903ca1c3ce"
    client_secret: "d092bd2b51a075fe7a790e01e8a2b1a8176a2d40"
    organization: "tiktok"
    application: "e-commence"
    frontend_url: "http://localhost:3000"
