// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"context"
)

type Querier interface {
	//CreatAddress
	//
	//  INSERT INTO addresses.addresses(owner, name, street_address, city, state, country, zip_code)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7)
	//  RETURNING id, owner, name, street_address, city, state, country, zip_code
	CreatAddress(ctx context.Context, arg CreatAddressParams) (AddressesAddresses, error)
	//DeleteAddress
	//
	//  DELETE
	//  FROM addresses.addresses
	//  WHERE id = $1
	//    AND owner = $2
	//    AND name = $3
	//  RETURNING id, owner, name, street_address, city, state, country, zip_code
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) (AddressesAddresses, error)
	//GetAddresses
	//
	//  SELECT id, owner, name, street_address, city, state, country, zip_code
	//  FROM addresses.addresses
	//  WHERE owner = $1
	//    AND name = $2
	GetAddresses(ctx context.Context, arg GetAddressesParams) ([]AddressesAddresses, error)
	//UpdateAddress
	//
	//  UPDATE addresses.addresses
	//  SET street_address = coalesce($1, street_address),
	//      city           = coalesce($2, city),
	//      state          = coalesce($3, state),
	//      country        = coalesce($4, country),
	//      zip_code       = coalesce($5, zip_code)
	//  WHERE id = $6
	//    AND owner = $7
	//    AND name = $8
	//  RETURNING id, owner, name, street_address, city, state, country, zip_code
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (AddressesAddresses, error)
}

var _ Querier = (*Queries)(nil)
