services:

  casdoor:
    image: casbin/casdoor
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/conf
    networks:
      - app-network

networks:
  app-network:
    external: true

